export const disclaimer = `
/*
 * This file was generated by graphql-code-generator with the apollo-hooks-codegen plugin.
 * Any changes made to the file will be overwritten.
 */
`;

export const imports = `
import gql from 'graphql-tag';
import { DocumentNode } from 'graphql';
import * as Urql from 'urql';
`;

export const boilerplate = `
/*
 * Boilerplate
 */

const queryDefaultOptions = {
    fetchPolicy: 'cache-and-network' as 'cache-and-network',
};

`;
